apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-webapp
  namespace: pwdmg
spec:
  selector:
    matchLabels:
      app: client-webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: client-webapp
    spec:
      containers:
      - name: client-webapp
        image: capy0812/pwd-client-k8s:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 3000