apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  namespace: pwdmg
data:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: pwdmg
  PGDATA: /var/lib/postgresql/data/pgdata